FROM ubuntu:22.04

RUN apt update
RUN apt install -y git wget

WORKDIR /app
RUN git clone https://github.com/ggerganov/whisper.cpp.git

WORKDIR /app/whisper.cpp

RUN ./models/download-ggml-model.sh small

RUN apt install -y build-essential libssl-dev libffi-dev cmake libatlas-base-dev gfortran
RUN make server

CMD ["./server", "-m", "models/ggml-small.bin", "--host", "0.0.0.0", "-l", "ja"]
