services:
  whisper:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: whisper
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
